import AppContext from "./AppContext/page";
import "bootstrap/dist/css/bootstrap.min.css"; 

import "./globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body>
        <AppContext>
        {children}
        </AppContext>
      </body>
    </html>
  );
}
